### PR TITLE
Feature/search activity

### PR DESCRIPTION
**Pull request by waithethtetoo**
change SearchView to AutoCompleteTextView at SearchActivity.java;

### CODE REVIEW

**Comment by vincent-paing** [comment]
@waithethtetoo Are you sure this feature is completed?

**Comment by waithethtetoo** [comment]
I have to implement search function.

**Comment by vincent-paing** [comment]
@waithethtetoo  so it's not finish? or do you want to implement search function in another feature branch?

**Comment by waithethtetoo** [comment]
bro @vincent-paing , I will use new feature branch for it. It can be OK  for me .

**Pull request merged**
